### ISSUE TITLE
Mining Settings: Continuous mining

### ISSUE THREAD

**Issue by unproductivityfriendly** [Farigh/pokeclicker-automation#105]
### Is your feature request related to a problem? Please describe.
For now, the fatest way to farm treasure items is to use Focus.Quest
Below is a simple solution for people who have an abundance of money to farm

### Describe the solution you'd like
Add an option to enable continuous mining by using Restore items : 
Toggle On/Off to enable continuous mining (uses a Restore item when the energy reaches 10 or less)
Similar to the Auto Shop settings, add toggle for each kind of Restore Item and the minimum amount when it stops using them.

### Additional context
None

**Comment by Farigh** [comment]
Will be done via  #62
