### ISSUE TITLE
Mining: Allow buy and use of small restore.

### ISSUE THREAD

**Issue by linkdest** [Farigh/pokeclicker-automation#106]
Currently we can only use that option in the focus mode. But if you play if amulet coin, lucky incense and have some amount of achievements, you can run mining non stop. It would be great have that option so we can farm more diamonds for full upgrades or for the hatchery helper.

**Comment by Farigh** [comment]
I plan to add a Focus on diamond via #62, I'll consider a general setting for that at that moment.
