### ISSUE TITLE
More focus

### ISSUE THREAD

**Issue by Yzar91** [Farigh/pokeclicker-automation#119]
Please, add more focus option.

mining ( automatically use spray)

shining ( use hatchery and combo starf and oak item)

Ev ( focalise on route and hatchery whereas the pokemon swap infected to cure)

**Comment by Farigh** [comment]
Mining (actually Diamond) focus has already been asked via #62

I'm not sure what you would expect about the other two, could you please provide a bit more details about the expected behaviour ? (preferably in dedicated issues)

**Comment by Farigh** [comment]
Split in #121  and #122
