### ISSUE TITLE
Autohatchery breeds certain shiny pokemon variants while set on "consider shiny pokemon last"

### ISSUE THREAD

**Issue by DaniLoscos** [Farigh/pokeclicker-automation#139]
### Describe the bug
Autohatchery keeps breeding certain shiny pokemon variants (Surfing Pikachu + Flying Pikachu) while set on "consider shiny pokemon last" even when other non shiny pokemon can be bred. Other shiny pokemon are not being bred.

### Steps to Reproduce
1. Have some shiny and some not shiny pokemon. Have shiny Surfing Pikachu + Flying Pikachu
2. Enable autohatchery.
4. Select "consider shiny pokemon last"
5. See error.

### Expected behavior
Only non shiny pokemon shoould be bred if you have them available

**Comment by Farigh** [comment]
Do you have, by any chance, set another setting, such as region of type filtering ?

Those settings are considered first as explained in #130.
If you chose lets say Electric filtering and only have a few electric pokémon that are not shiny, it will add non-shiny electric pokémons, then shiny electric ones and finally non-electic non-shiny ones

**Comment by DaniLoscos** [comment]
The only other conflicting stting may be "Focus on speading Pokérus" dropdown settings are "Any, Any, None", Hatchery filter is set to just "Non Shiny".

**Comment by Farigh** [comment]
Could you provide a save file reproducing the problem ?

**Comment by DaniLoscos** [comment]
Disabling "Focus on speading Pokérus" resolved the issue. 

I play using several Ephenia scripts therefore the savafile may not be compatible with the original game:
![image](https://user-images.githubusercontent.com/11975716/192090592-9a9dd61f-5d61-4c57-9559-237f09c18da3.png)
[[v0.9.16] PokeClickerSave_2022-09-24 09_23_44.txt](https://github.com/Farigh/pokeclicker-automation/files/9638354/v0.9.16.PokeClickerSave_2022-09-24.09_23_44.txt)

**Comment by Farigh** [comment]
Have you tried disabling any of your other scripts ? Did it change anything ?

**Comment by DaniLoscos** [comment]
Disabling the other scripts did no show any change in behavior. 

It must be the pokerus speading. Thank you!
