### ISSUE TITLE
Auto dungeon not working

### ISSUE THREAD

**Issue by jennsgaming** [Farigh/pokeclicker-automation#140]
### Describe the bug.
With the new update changing how dungeons are done the auto function no longer works

### Expected behavior
dungeon should complete its self

**Comment by Farigh** [comment]
I'll take a look in the coming days, I'll not have time tomorrow.
Sorry for the inconveniences.

**Comment by Farigh** [comment]
I'll take a look soon.
This part lacks automated testing unfortunately.
I must have missed something in my manual ones....

**Comment by kagejohn** [comment]
positionToCheck is missing floor, an example fix: https://github.com/kagejohn/pokeclicker-automation/commit/e830acf6098d71e1dc7bb2bf3e6df72260a52178

**Comment by Farigh** [comment]
Ho I forgot to check the BossRush behavior, I'll perform a bit more testing and push a fix

**Comment by Farigh** [comment]
@kagejohn Thanks for the hint

It should work properly now :)
