### ISSUE TITLE
Dungeon: Handle multiple floors instances

### ISSUE THREAD

**Issue by Farigh** [Farigh/pokeclicker-automation#142]
### Describe the bug
The #141 PR issued a dirty fixe to changes made for the upcoming Galar region.
Dungeon will be able to grow bigger than 10 tiles large, such dungeon will be split in multiple floors.

The above-mentioned PR fixed the currently available content by always targeting the first floor.
However Galar will require a full rework to handle multiple floors and the new ladder mechanics.

[Pokeclicker changes](https://github.com/pokeclicker/pokeclicker/commit/97b201dfd1c1d421720290d4bbca808f94ce5cbe)

**Comment by BigJonSD** [comment]
The multiple floors dungeons are already active in the Alola region as well. I haven't tested all of them but it's definitely on for the Lake of the Sunne and Moone.
