### ISSUE TITLE
Automation Achievements Skips Over Dungeons.

### ISSUE THREAD

**Issue by Spooony** [Farigh/pokeclicker-automation#143]
### Describe the bug
When turning on automatic achievements, if there's dungeons left in the region, it will not complete them and move to the next region.

### Steps to Reproduce
Click drop down and select Achievements,
Click "off" to "on"
Watch as it will skip your dungeons that aren't completed.

### Expected behavior
Should complete dungeons before moving to next region

**Comment by Farigh** [comment]
Are set dungeon unlocked ? 
Could you provide a save reproducing the issue ?

**Comment by Spooony** [comment]
> 
All dungeons are open and ready to complete. The save I've attached, I have not finished Sinnoh dungeons but when "Focus on: Achievement" is switched on, it switches to Unova's route achievements. 
[[v0.9.18] PokeClickerSave_2022-10-11 22_46_58.txt](https://github.com/Farigh/pokeclicker-automation/files/9760165/v0.9.18.PokeClickerSave_2022-10-11.22_46_58.txt)

**Comment by kagejohn** [comment]
probably a chrome issue: i tried with the fix you made for the other cases: https://github.com/Farigh/pokeclicker-automation/commit/b81a819c3bc5a7bfde9090f0ffeb48dcac876757
adding `if (a.region === b.region) return 0;` fixed it for me: https://github.com/kagejohn/pokeclicker-automation/commit/312b21d81e7df21f1f603ebce98fff4ffef58825
