### ISSUE TITLE
Hatchery focus on non shiny from a specific region ends up with other region shinies in hatchery

### ISSUE THREAD

**Issue by SOKS33** [Farigh/pokeclicker-automation#144]
### Steps to Reproduce
1. Have < 10 missing shinies from a region
2. Focus on this region in hatchery + focus on getting new shinies only (with/without pokerus focus is the same I believe)
3. When all the missing shinies are still leveling up (not eligible for hatchery), other shinies go into the hatchery
4. Enjoy hatched shinies

### Expected behavior
Other regions **non-shiny** pokemons should be used

### Additional context
This is between a bug and an enhancement

**Comment by Farigh** [comment]
This is the intended  behaviour for now.
It will be fixed once filters reordering is implemented via #130
