### ISSUE TITLE
Farming: Does not Harvest while using Petaya

### ISSUE THREAD

**Issue by unproductivityfriendly** [Farigh/pokeclicker-automation#151]
### Describe the bug
Farming does not Harvest non-locked berries while they are affected by Petaya

### Steps to Reproduce
1. Farm
2. Ripe Petaya and other berries
3. Lock Petaya and berries you don't want to Harvest
4. Non-locked ripe berries are not harvested

### Expected behavior
Non-locked ripe berries should be harvested and replanted when they are affected by Petaya

### Additional context
![image](https://user-images.githubusercontent.com/46303932/197167183-7332d13f-f734-4364-8394-bef61d0e9b83.png)

**Comment by Farigh** [comment]
I'm not sure why the berries does not get harvested.

Could you provide a save reproducing this issue ?

**Comment by Farigh** [comment]
@unproductivityfriendly Can you confirme the problem has been fixed ? I don't have time right now to reproduce your use-case

**Comment by Farigh** [comment]
I'm closing this, feel free to reopen it if the problem persists

**Comment by unproductivityfriendly** [comment]
Yep it's fixed, thanks
