### ISSUE TITLE
Dungeon: Option to select a pokéball for the boss

### ISSUE THREAD

**Issue by unproductivityfriendly** [Farigh/pokeclicker-automation#154]
### Is your feature request related to a problem? Please describe.
Right now, if we want to farm the dungeon boss for EV or Shiny, we need to set Caught/Caught Shiny Pokéball, and have to attempt capturing every pokémon encounter in the dungeon.

### Describe the solution you'd like
Add a setting for dungeon to select a Pokéball type for the Dungeon boss
Even if we have the Caught Pokéball set to None, it will equip the pokéball selected temporarily before fighting the boss, and remove it/put back to previous setting after leaving the dungeon.

**Comment by Farigh** [comment]
This would be a bit complicated, since most dungeon can have multiple bosses.
I could try to implement a first version switching for pokeballs on the boss no matter the boss pokemon.

However, I'm wandering if it wouldn't be better to have a new "auto-catch" feature were the player could choose pokemon(s ?) to always catch (even though it would require a new menu to allow such choice).

Note: There are a lot of issues to implement a catch filter within the game

**Comment by unproductivityfriendly** [comment]
>This would be a bit complicated, since most dungeon can have multiple bosses.

Yes, I meant equiping before any boss encounter would be fine

>new "auto-catch" feature were the player could choose pokemon(s ?) to always catch 

Is it possible to know which pokemon you are going to encounter before the fight? That would be against the philosophy of the script no?


Something I think that could be good to have, toggle for each kind of pokéballs:
When Ultraball (+10%) is selected to caught pokémons, the following behaviors can be enabled to increase catchrate
Quickball: always use when route kill is between 0 and 152
Timerball: always use when route kill is above 7790
Duskball: at night or in dungeon, OR only for dungeon boss
Diveball: in water environments
Lureball: when fished
Nestball: [see best case on wiki](https://pokeclicker.miraheze.org/wiki/Nestball)
Repeatball: if the pokémon has been caught 224 times and toggle EV farming

**Comment by Farigh** [comment]
> Is it possible to know which pokemon you are going to encounter before the fight? That would be against the philosophy of the script no?

You're right it's a bit borderline, and many player requested this in game, so it might come in the near futur. So I better not bother

Considering the 'contextual' ball selection, it would be it bit complicated
