### ISSUE TITLE
Auto handle equip items

### ISSUE THREAD

**Issue by Daniferrito** [Farigh/pokeclicker-automation#172]
### Is your feature request related to a problem? Please describe.
It is a hassle to calculate which combination of equip items is the best.
It should be trivial to calculate the optimal combination and automatically equip it.

### Describe the solution you'd like
Most equip items are simply "Increase attack of pokemon with <x> limitation by y%" so they are easily comparable.
The only two unique items are "15% increased exp gain" and "100% increased EV gain". For a first version, it should keep those as they are (do not remove them if they are equiped, do not equip them if they are not).
For the rest of the items:
* Until all slots are used
  * For each unequiped item
    * Calculate the pokemon that can equip it with the greatest attack
    * Calculate the attack increase by equiping it
  * Choose the one with the greatest attack increase and equip it to that pokemon
Every once in a while (5 to 30 minutes?), recalculate this in case it has changed. The lazy way would be to unequip everything and then redo the algorith above.

### Additional context
A future feature might be advanced options to auto equip the exp and EV items.
* The exp item should be equiped to the non lvl 100 pokemon with the highest priority acording to the hatchery ordering
* The EV item should be equiped to the pokérus infected pokemon with the lowest EV total that appears in the current route/dungeon
Issues here is what to do if the pokemon to equip already has a stat-boosting item

**Comment by Farigh** [comment]
Wouldn't unequipping the item destroy it ?

https://github.com/pokeclicker/pokeclicker/blob/5e80efb979086e89bc0e5093f1ec69bcaf06d046/src/scripts/party/PartyPokemon.ts#L291

**Comment by Daniferrito** [comment]
That is a very weird design decision, and totally oposite of how the main games work. 

Seeing as this is the case, then the whole idea no longer makes much sense, and would need to be reworked.

Maybe as a calculator to see which pokemons to equip? That works better as its own tool, and I dont think it fits this one.

I suggest to close this sugestion as a poor fit for the tool

**Comment by Farigh** [comment]
We could indeed consider building a tool in a modal later on, this would be great
