### ISSUE TITLE
Focus.Quest: Option to exclude all automated farm actions

### ISSUE THREAD

**Issue by dox4242** [Farigh/pokeclicker-automation#175]
### Is your feature request related to a problem? Please describe.
While grinding up quest coins, I can't figure out how to get the farm excluded from automated actions. I set the options for Focus.Quests to skip the farm points and berry harvest quests, and I keep Focus.Farming turned off all the time, even though it seems disabled when Focus.Quests is active. But Cheri berries still keep being automatically planted and harvested. Sometimes, the last berry I selected gets automated, for a few minutes, before the scripts switch to Cheris. (Maybe I don't understand the instructions properly.)

### Describe the solution you'd like
Include a new "Focus on" advanced setting to exclude all farm actions from automation.

### Describe alternatives you've considered
Alternately, this feature request issue should instead be a bug report issue for the Focus.Farming toggle switch not working when Focus.Quests is active.

**Comment by Farigh** [comment]
I was just about to implement it this week as a toggle and do it as well if no farm quests are enabled.

For now you can do `` in the console after enabling the focus (as it's only set at the beginning).
