### ISSUE TITLE
Trivia: Alcremie.

### ISSUE THREAD

**Issue by linkdest** [Farigh/pokeclicker-automation#181]
Galar was introduced and now we have alcremies and have to track the spins. It would be a great QoL if there was a way to track how many times we have spin clockwise and counterclockwise at the certain time. I imagine as a table with the column being the sweet and the line day/night/dusk. There is a bigger table at the battle café page in the wiki.

**Comment by Daniferrito** [comment]
Where do you think we should show this? It would preferably be visible while the battle cafe is open (simply dont close it when opening the battle cafe would work)

Maybe having it as an advanced options inside the "available evolutions" part of the trivia viewer?

**Comment by Farigh** [comment]
We could indeed use the `BattleCafeController.evolutions` to get the forms of the currently selected sweet.
I would prefer a new panel, like gym and dungeon fights, that would only show while in BattleCafé and only show info about the currently selected sweet.

I'll work on this right away.
