### ISSUE TITLE
Auto Shop Uncaught TypeError

### ISSUE THREAD

**Issue by asomness2** [Farigh/pokeclicker-automation#184]
### Describe the bug
The script update is erroring with "Uncaught TypeError: this.__internal__isPokeMarkUnlocked is not a function" breaking the Auto Shop functionality.

### Steps to Reproduce
1. Load script
2. Enable any item to be auto bought.
3. "Uncaught TypeError: this.__internal__isPokeMarkUnlocked is not a function" error in browser console every shop check

### Additional context
First noticed on Firefox for Windows 10, confirmed again with Edge browser on a fresh save played up to auto shop being unlocked

**Comment by Farigh** [comment]
That should be fixed, sorry for the inconvenience
