### ISSUE TITLE
New pokeclicker version breaks the scripts

### ISSUE THREAD

**Issue by Daniferrito** [Farigh/pokeclicker-automation#186]
### Describe the bug
The next version of pokeclicker refactors some code, moving most items into modules. This breaks some code (like the auto-shop), as the classes to check for instanceof are no longer global objects

### Steps to Reproduce
Launch the develop version of pokeclicker (or just wait a few days for it to get into production)
Load the scripts and open the developer tools

### Additional context
I have not checked how to access (or if it is even accessible now) the class definitions inside modules.

**Comment by Farigh** [comment]
@Daniferrito are you working on this ?
If so can you assign yourself to the issue ?

**Comment by Daniferrito** [comment]
I am currently not, as I dont know how to actually solve it. I will study it some more, but from my preliminary searches, it does not look promising.

If you know how to get a reference to an export of a module, let me know.

I am willing to do the work to gather all the references in some utility file and patch the code to use them, but I dont know how to do it.

**Comment by Daniferrito** [comment]
Also, I am not able to assign issues to anyone, not even to myself. I cannot assign PR reviewers either.

**Comment by Farigh** [comment]
Hum I did not find a way to grand you issue rights.
The interface is not the same as GitHub Enterprise, maybe because it's a personal repository, and not an organisation one.

Anyway, I've assigned myself, I'll try to work on it before the next update rolls out

**Comment by Farigh** [comment]
Hum I just tried the current develop HEAD and everything look fine to me: 
![image](https://user-images.githubusercontent.com/11090416/200638879-3c6f5767-814d-4c27-86c3-f1a239f41931.png)

As a proof, I've got your change : 
![image](https://user-images.githubusercontent.com/11090416/200638950-22d7e04c-c8d8-4087-8965-863e1106a126.png)

Even though the types comes from modules, they are available as before (which is logic, as it would have required so much changes to the pokeclicker's code otherwise):
![image](https://user-images.githubusercontent.com/11090416/200639453-8528c491-1483-4fc2-bd50-6ac1f19f4ff8.png) 

Did you, by any chance, run the script on a fresh save ?
By default, items are not displayed unless you unlocked a location to purchase those, the menu would then look like this:
(we should hide the tab when no items are available, is such case, I'll do that shortly).
![image](https://user-images.githubusercontent.com/11090416/200640058-ec895f51-ac1b-445a-9fa8-2a02aaec3443.png)

**Comment by Daniferrito** [comment]
Make sure to make the fetch, as I'm not sure you are looking at the correct version. The relevant PR is number 3305 (making sure to not link it), and the commit is https://github.com/pokeclicker/pokeclicker/pull/3305/commits/0b21a4ac30b39a2908d0e8f8281150ef93de7645

![Console errors](https://user-images.githubusercontent.com/2537742/200642082-dce90bb8-f717-4f3e-9938-fad6d6061641.png)

Not all the things dissapeared. For now, only the Item subclasses dissapeared (But not the base Item)

**Comment by Farigh** [comment]
Hum, I'm using the pokeclicker Desktop app to serve the develop branch and do not have this problem: 
![image](https://user-images.githubusercontent.com/11090416/200655797-0bc43799-c584-4716-a91f-df8e67067a72.png)

AFAIK the eletron app uses the same engine as chrome (chromium to be honest), which you seem to be using.
So we should have the same behavior.

I tried with local sources on both Chrome and Firefox and did not see any problem either...

Are you running a server, or did you just download the files locally and open the index.html in your browser ?
If you run a server, this might change things a bit, and I might have to try adding pokeclicker to my test-server to reproduce then.

**Comment by Daniferrito** [comment]
I'm running it locally with their start script inside package.json

I will try both with the Desktop app and compiling it. If the problem only affects running it from source without compiling, then there is no issue (I still think you might be using an old version, but I'm going to try anyways)

**Comment by Daniferrito** [comment]
I just finished checking. 

Compiling it locally, it also displays the problem.
Running it through Pokeclicker Desktop will not display the problem, because even if you point it to the develop branch, it will ignore everything and use the files in the docs folder, which are only regenerated when new versions are published, so they still have the old version.

To run it through Pokeclicker Desktop, you would need to create a branch (or really a fork), compile it (with the `website` script), and push to the repo after compiling, then change Pokeclicker Desktop to use that specific git repo/branch with the compiled code.

To check that you are in the most recent version, you can look at the Indigo Plateau in Johto. If you see a hiker, you are in the most recent version. If you do not see a hiker, you are in the current version (or an older one)

**Comment by Farigh** [comment]
Hum I see, I might have over-interpreted the fact that I had the .subRegion available on towns then, I'll spend more time on it latter this week.
Thanks for the walkthrough :)

**Comment by Daniferrito** [comment]
The subRegion has been available since a long time ago. However, all of them (except some dungeons) have a 0 in the field.

The PR i made is to actually put data in that field, instead of leaving the default value of 0

**Comment by Farigh** [comment]
Would you mind zipping a version of the compiled last develop commit for me ? 
I'm do not have the right environment (I'm not a web dev, I only do it for fun, I'm a C++ dev) and it would help me get into it quicker.

**Comment by Daniferrito** [comment]
I just compiled and uploaded it to my fork.
You can download the code directly from https://github.com/Daniferrito/pokeclicker
Or even easier, just open the game directly from my compilation version: https://daniferrito.github.io/pokeclicker/

You can see the problem there
