### ISSUE TITLE
Dungeon Focus is broken

### ISSUE THREAD

**Issue by cfedey** [Farigh/pokeclicker-automation#191]
### Describe the bug
When enabling the Achievements Focus, the script disables it and reports there are no more achievements to automate, even though there are.

### Steps to Reproduce
0. (In my case) Have only dungeon achievements and the 20-million Farm Point achievement remaining to do.
1. Activate the Achievement Focus.
2. Wait a second.
3. The Achievement Focus is automatically disabled and nothing else has happened.

### Expected behavior
1. Activate the Achievement Focus.
2. The next achievement in the list is automated, as described in the Wiki.
3. Achievements are automated until no more route/gym/dungeon achievements remain.

### Additional context
Initially noticed last night after a game restart on v0.4, but updated to v0.5 today and it still persists. Was working fine until I restarted the game last night, and I try to restart it once a day to download new updates.

It can be worked around by using the Dungeon Fight tool, but this requires manual input eventually to change the dungeon.

The other Focuses work fine.

Game version 0.10.1.

![image](https://user-images.githubusercontent.com/103959912/200844874-8ad55dca-0375-47bb-9454-ed7c1ebb69c4.png)

**Comment by Farigh** [comment]
Do you have a save reproducing ? I do not have any with only dungeon achievements.

I fixed a bug yesterday about this, that was behaving this way for routes, on chrome, their might be some more to fix.

**Comment by cfedey** [comment]
[[v0.10.0] PokeClickerSave.txt](https://github.com/Farigh/pokeclicker-automation/files/9973622/v0.10.0.PokeClickerSave.txt)

Here's a save I just made. Let me know if you need any more info.

**Comment by Farigh** [comment]
Thanks for the quick reply. In the mean time, I found a way to complete all achievements of a set type and reproduce the problem.

This is tied to the problem I partially addressed yesterday. I'll push a fix in a few minutes.

**Comment by Farigh** [comment]
This should be working properly now (you might have to disable you browser cash if you refreshed not long ago)

**Comment by cfedey** [comment]
It does work now. Thanks very much.
