### ISSUE TITLE
Have settings disabled by default

### ISSUE THREAD

**Issue by RemixV4** [Farigh/pokeclicker-automation#194]
Would it be possible to have all the options disabled by default? Every time I load my save onto a new browser or computer, everything's already turned on and it messes up my setups for things like farming and mining.

The most recent example being that the auto-trade feature converted a bunch of treasures I was saving for a chain, screwing me out of a ton of diamonds. I didn't even notice the feature was added until after I replaced my save, so I can't get my stuff back.

**Comment by Farigh** [comment]
It's not an option per says but it was already implemented and explained here #152

I need to update the wiki

**Comment by RemixV4** [comment]
Maybe I'm using it wrong, but it only disabled the main buttons for me. The options under the tabs are still auto enabled, so my example scenario would still happen.

**Comment by Farigh** [comment]
The elements of the tabs are not active unless the feature is enabled anyway

**Comment by RemixV4** [comment]
Right, but if something like a new Mining option is added while I have Mining enabled, the new option would still be auto enabled.

**Comment by Farigh** [comment]
Hum, I'll try to disable setting as well by default

**Comment by Farigh** [comment]
I updated the configuration to be able to disable settings as well : 
https://github.com/Farigh/pokeclicker-automation/blob/master/Automation-UserScript.js

**Comment by RemixV4** [comment]
Excellent, it seems to be working perfectly. Thank you!

**Comment by Farigh** [comment]
The wiki has been updated accordingly ([\[EN\]](https://github.com/Farigh/pokeclicker-automation/wiki/How-to-Setup-the-UserScript) | [\[FR\]](https://github.com/Farigh/pokeclicker-automation/wiki/Comment-installer-le-UserScript))
