### ISSUE TITLE
Quest: Allow the player to ignore some quest types

### ISSUE THREAD

**Issue by Farigh** [Farigh/pokeclicker-automation#20]
Some quests can be pretty long to complete.
It would be useful to be able to be able to ignore some quest types, and automatically refresh the quest list if all but those quest type are completed.

This would allow to speed-up the process at a small fee (the refresh cost)

Suggested by #18

**Comment by Farigh** [comment]
In the same vein, add the ability to reorder quest priority

Suggested by `darthcid` on reddit

**Comment by Nox-Ater** [comment]
With the new achievements of the Quest, I think it's important to finally be able to choose what kind of quests not to do in order to progress faster.

**Comment by Farigh** [comment]
I don't have that much time at the moment.
I'll probably work on this one next.

I'll try to do it in the coming days
