### ISSUE TITLE
Hatchery: Focus on mega-evolvable pokemon with missing requirements

### ISSUE THREAD

**Issue by Daniferrito** [Farigh/pokeclicker-automation#201]
### Is your feature request related to a problem? Please describe.
The new megaevolutions add an attack requirement to do the megaevolution. This means that the pokemon needs to be focused in the hatchery over other things

### Describe the solution you'd like
Add an option in the hatchery to focus on pokemon that can megaevolve but dont have the requirement yet

**Comment by Farigh** [comment]
I played around with the game, and it seems we could get those pokémon with this filter:
`App.game.party.caughtPokemon.filter(p => p.evolutions?.some(e => (e.trigger == EvoTrigger.STONE) && (e.stone == GameConstants.StoneType.Key_stone))) `

**Comment by Daniferrito** [comment]
This would return all pokemons that COULD megaevolve, but the player might not have the megastone for it yet.

This is probably fine anyways, as the requirement is harcoded to "attack is 100 times the base attack", so it is somewhat easy to get (around 150 hatches, I believe).

On the other hand, once all megastones are added, it would be 45 of them, so getting all of them to 150 hatches would be much longer.

In this case, I vote to leave it as you posted, just all pokemons that could evolve, even if the player does not have the stone yet. It is optional anyways.

Even if it is hardcoded to 100 times, I would still use the `p.megaStone?.attackRequired` to check, in case some other have higher requirements. 

This check is very important, as once the requirement is met, it no longer is better to breed this pokemon over other ones

**Comment by Farigh** [comment]
Yes I just saw that, I was looking at the pokéclicker code and I found this : 
```javascript 
PokemonHelper.getPokemonsWithEvolution(GameConstants.StoneType.Key_stone)
```
