### ISSUE TITLE
10.2 update seems to break the script

### ISSUE THREAD

**Issue by TheSaucyWelshman** [Farigh/pokeclicker-automation#202]
### Describe the bug
After refreshing the page to update to 10.2 the only thing that loads in the automation box is the auto clicker.

### Steps to Reproduce
Load script on version 10.2

### Expected behavior
It should be loading all of the modules.

### Additional context
Just tried the desktop client with scripts and it's having the same issue.

**Comment by ssiatkowski** [comment]
I have the same issue. Want to add that I have a separate AC save that's up to Hoenn where the script works fine, so it's likely that some later functionality is breaking the script.

**Comment by AnnoyingPriannacompy** [comment]
it's Probably The Magikarp section or the New Exclusive content.

**Comment by Farigh** [comment]
I'm currently not close to a computer, I'll take a look in 2-3 days
