### ISSUE TITLE
Quest focus locking up in certain situations.

### ISSUE THREAD

**Issue by cfedey** [Farigh/pokeclicker-automation#211]
### Describe the bug
While using the Quest focus, the script won't automate collection of grass gems if it chooses Lush Jungle as the place to get the gems from.

### Steps to Reproduce
1. Have a "collect grass gems" quest.
2. Be at a certain level of progression that Lush Jungle is the most efficient place chosen by the script to get grass gems from (I assume this is how the script operates).
3. Enable Quest focus.
4. Script navigates to the Lush Jungle dungeon screen but doesn't start the dungeon.

### Expected behavior
The script should automate catching in Lush Jungle to collect grass gems for the duration of the quest.

### Additional context
I'm not sure exactly what combination of variables lining up caused this. The focus was working fine as it usually does, but something about the grass gem quest caused it to lock up. I was away for about 20 minutes so I didn't see it happen. To try to get it to move again I disabled completion of certain quest types one at a time, and only after the "collect gems" quest type was disabled in the Focus settings did the script continue with the other remaining quests.

Also, while trying random things to get it to work I disabled my Black Flute, and the script started working again. So it might be something about how much click attack I have with the Flute on. Not sure if lacking X Click would have a similar effect, since I have too much duration remaining on that to test. Rocky Helmet was also used. 

Click attack without Black Flute: 2,296,262
Click attack with Black Flute: 2,812,922

Pokeclicker v0.10.6
Client with scripts v1.2.0

Let me know if you need more info.

**Comment by Farigh** [comment]
Can you provide a save reproducing the problem ?
Since it does not always reproduce it might be tricky to reproduce and thus fix this issue without one.

**Comment by Farigh** [comment]
Additionally, does the `Focus on Grass gems` reproduce ? (it might be easier to reproduce this way with your current save if it does not have this specific quest atm)

**Comment by cfedey** [comment]
[[v0.10.6] PokeClickerSave.txt](https://github.com/Farigh/pokeclicker-automation/files/10347001/v0.10.6.PokeClickerSave.txt)
This save currently has a fire gems quest that acts the same as the grass gems quest issue. It tries to go to Wela Volcano Park to presumably get fire gems there, and gets stuck on the dungeon entrance screen.



> Additionally, does the `Focus on Grass gems` reproduce ? (it might be easier to reproduce this way with your current save if it does not have this specific quest atm)

Yes, it does, as do an assortment of other Gem Focuses. Ones that work fine are ones where the script picks a gym leader to get gems from. Ones that get stuck are ones where it picks an Alola dungeon to get gems from. Not sure if it would get stuck on any other region's dungeons, since it only either chose gym leaders or Alola dungeons to get gems from, and if I remove Rocky Helmet and/or Black Flute it swaps to farming gym leaders for gems instead of the dungeon.

**Comment by Farigh** [comment]
Thanks a lot, I'll take a look next week, as soon as I get some time

**Comment by cfedey** [comment]
Thanks. 

For anyone else with this issue: the workaround is to try turning off Black Flute or removing Rocky Helmet or otherwise lowering Click Attack so the script picks another location to get gems from.

**Comment by Farigh** [comment]
This should work properly now (at least it does in the case of your save file) ;)
