### ISSUE TITLE
Auto shop advanced settings ignores Minimum Currency Setting

### ISSUE THREAD

**Issue by lmikulla** [Farigh/pokeclicker-automation#213]
The setting in the auto shop advanced settings "Stop buying if the player has less than x currency" does not get applied. The shopping logic instead always uses the default value.

1. Go to auto shop advanced settings 
2. Increase or decrease the "Stop buying if the player has less than x currency" setting for any currency
3. Make sure there is something that will be bought
4. If the limit is raised above the default value, the autoshop logic will keep buying even if under that limit (till the default value). If the limit is lowered below the default value, the logic will not buy anything until the default value of currency is reached

**Comment by lmikulla** [comment]
From a quick read, i believe @ https://github.com/Farigh/pokeclicker-automation/blob/master/src/lib/Shop.js#L236
Is missing a reference to the type of minimum currency that is being set.

**Comment by Farigh** [comment]
O.o good catch !

None of the values as actually saved ... I'll fix that right away !

**Comment by Farigh** [comment]
This should be working properly now, if not, feel free to reopen this issue
