### ISSUE TITLE
Focus on Gems should use gyms/dungeons

### ISSUE THREAD

**Issue by PelvodelFuego** [Farigh/pokeclicker-automation#22]
Setting the focus to dragon gems goes to Johto Route 45, which was gaining me ~33 gems per minute. For comparison the Blackthorn City Gym brings in ~1600 gems/minute. Assuming you can access them, the Kanto/Johto gyms should always be the most efficient for gem farming for all types except Fairy.

**Comment by Farigh** [comment]
I don't consider dungeon a better alternative for gems, but I can surly add gyms.
