### ISSUE TITLE
Focus.Quests: Berries are still being harvested even with Farm Automation disabled

### ISSUE THREAD

**Issue by RemixV4** [Farigh/pokeclicker-automation#224]
### Describe the bug
Whenever I use Focus on Quests, all of my berry plots that aren't currently locked are immediately harvested and replanted, as if farming automation is on. My farming automation is definitely off, I have no farm hands active, even my settings for Focus Quests currently have the "Gain Farm Points" and "Harvest Berries" quests off too. There's no reason for it to be happening.

### Expected behavior
When using Focus on Quests, berries shouldn't be harvested/planted if farming automation is set to off.

**Comment by Farigh** [comment]
This behaviour is by design.
Unless you disabled farming related quests, the focus will force the farming automation to run.

If you don't want it to run, you only have to disable those quest types from the advanced settings panel

**Comment by RemixV4** [comment]
On your note, the farm automation button doesn't grey out like the others.

**Comment by Farigh** [comment]
It should be working properly now
