### ISSUE TITLE
Auto dungeon and elite battles are gone in the newest pokeclicker update

### ISSUE THREAD

**Issue by iIoli** [Farigh/pokeclicker-automation#227]
Yeah
<img width="159" alt="Screenshot 2023-01-28 at 11 08 09 AM" src="https://user-images.githubusercontent.com/63279082/215239033-087d33e7-5efe-4ab7-8758-395605f7597f.png">

**Comment by iIoli** [comment]
Possible evolution is also not working properly

**Comment by Essoheli** [comment]
Uncaught TypeError: PokemonHelper.getPokemonsWithEvolution is not a function
    __internal__hasStoneEvolutionCandidate https://www.pokeclicker.com/# line 90 > injectedScript:497
    evoStones https://www.pokeclicker.com/# line 90 > injectedScript:440
    __internal__refreshEvolutionTrivia https://www.pokeclicker.com/# line 90 > injectedScript:439
    __internal__initializeEvolutionTrivia https://www.pokeclicker.com/# line 90 > injectedScript:425
    initialize https://www.pokeclicker.com/# line 90 > injectedScript:21
    timer https://www.pokeclicker.com/# line 90 > injectedScript:78
    setInterval handler*start https://www.pokeclicker.com/# line 90 > injectedScript:44
    watcher https://www.pokeclicker.com/# line 30 > injectedScript:157
www.pokeclicker.com:497:45
    __internal__hasStoneEvolutionCandidate https://www.pokeclicker.com/# line 90 > injectedScript:497
    evoStones https://www.pokeclicker.com/# line 90 > injectedScript:440
    filter self-hosted:241
    __internal__refreshEvolutionTrivia https://www.pokeclicker.com/# line 90 > injectedScript:439
    __internal__initializeEvolutionTrivia https://www.pokeclicker.com/# line 90 > injectedScript:425
    initialize https://www.pokeclicker.com/# line 90 > injectedScript:21
    timer https://www.pokeclicker.com/# line 90 > injectedScript:78
    <anonymous> self-hosted:1356
    (Async: setInterval handler)
    start https://www.pokeclicker.com/# line 90 > injectedScript:44
    watcher https://www.pokeclicker.com/# line 30 > injectedScript:157
    <anonymous> self-hosted:1356

**Comment by Essoheli** [comment]
Checking console on load up, getting this error, might be related.

**Comment by Farigh** [comment]
Everything should be back to normal
