### ISSUE TITLE
Auto dungeon dont work well with new flashlight

### ISSUE THREAD

**Issue by ahlfred** [Farigh/pokeclicker-automation#231]
Auto dungeon dont work 100%. Dont know how the new flash tiers work but i messes with auto dungeon. If i dont have any flash it works like normal but in like where i have 300+ it dont do that well. I have to help it reveal space in order for it to start doing it by itself.

**Comment by Farigh** [comment]
For now I disabled it, I created a new issue to put this strategy back #233
