### ISSUE TITLE
Auto dungeon fights randomly stop

### ISSUE THREAD

**Issue by iIoli** [Farigh/pokeclicker-automation#235]
It shows "user action detected, stopping automation" even though I didn't do anything. It does this even when the page is out of focus. It happens once every few dungeon clears.

**Comment by jerryrice88** [comment]
I also have this issue.

**Comment by Farigh** [comment]
I'll look at it once I get home.
I'll remove this check when the flashlight is unlocked

**Comment by Farigh** [comment]
The feature should not trigger while having the flashlight anymore
