### ISSUE TITLE
Hatchery: Add Sevii and Magikarp Island to the region list

### ISSUE THREAD

**Issue by linkdest** [Farigh/pokeclicker-automation#238]
Magikarps: Have an option to focus on magikarps when breeding. 

Mega Evolutions: I play the real evolution challenge. When I get the Mega, all the bonus goes to the evolution and the pokemon who evolves gets its base attack. The focus mega option still hatches the pokemon that i already have a mega evolution because of the low attack.

**Comment by iIoli** [comment]
I mean if you want to focus on magikarps just sort by egg steps ascending.

**Comment by linkdest** [comment]
That's a good idea when having many magikarps, i only have two. The idea is that it's possible tobreed by effiency while the magikarps are there too.

**Comment by unproductivityfriendly** [comment]
You can already do that by making a Hatchery Category and put all the magikarps in it.
Then in the Hatchery settings, sort by Category

**Comment by Farigh** [comment]
## Todo
- [ ] Add more precise region filters to the hatchery selector (sevii, magikarp ...)
- [ ] Don't consider mega evolution if they are already unlocked
