### ISSUE TITLE
Focus.Pokérus: Does not take weather into account

### ISSUE THREAD

**Issue by unproductivityfriendly** [Farigh/pokeclicker-automation#239]
### Describe the bug
When using **Pokérus cure** as focus, it does not take weather into account.
I get stuck on Hoenn Route 119 as it tries to hunt a Castform not available with the current weather.

### Steps to Reproduce
1. Have a Contagious Castform form
2. Make sure the current weather will not make that form appear
3. Select **Pokérus cure** as Focus and turn it **On**

### Expected behavior
Should take the weather into account, and go look for an other route that has available pokémon to hunt.

### Additional context
In the screenshot, you can see that the route has currently no contagious pokémon, but the focus is still on this route.

![image](https://user-images.githubusercontent.com/46303932/215343396-59388517-4d09-40f0-a4b1-d8a07097bf31.png)

**Comment by Farigh** [comment]
I pushed [bugfix/fixup-focus-pokeruscure-selecting-road-with-no-available-pokemon](https://github.com/Farigh/pokeclicker-automation/tree/bugfix/fixup-focus-pokeruscure-selecting-road-with-no-available-pokemon) with what a think could be the problem if you can test it (changing `master` to `bugfix/fixup-focus-pokeruscure-selecting-road-with-no-available-pokemon` in the `releaseLabel` variable of the loader)

**Comment by Farigh** [comment]
I managed to reproduce by forging a save reproducing your problem.

This should now work properly.
