### ISSUE TITLE
Blacklist achievements for auto-achievements

### ISSUE THREAD

**Issue by iIoli** [Farigh/pokeclicker-automation#240]
I'm doing all challenges right now and 100% magikarp jump is going to take me a whole year. Please make a blacklist feature for auto-achievements

**Comment by Farigh** [comment]
Blacklisting achievements might not be an easy task.
However, I'll consider adding a setting to skip the magikarp Ilsand.

**Comment by Farigh** [comment]
I added a new setting so you can complete the Magikarp Jump achievements last 
![image](https://user-images.githubusercontent.com/11090416/215853257-e18ceff2-9171-47b8-b346-309d08c0b409.png)
