### ISSUE TITLE
When the only quest left is "Hatch <n> eggs", the automation doesn't know what to do and halts. 

### ISSUE THREAD

**Issue by iIoli** [Farigh/pokeclicker-automation#249]

**Comment by Farigh** [comment]
Hi,

Could you provide a save reproducing your problem ?

**Comment by Farigh** [comment]
I did try filtering only those quests is the settings and I still have the intended behavior.
I even tried to go in a city and turn off the Farming automation.
The automation rightfully does the following : 
  - Force hatchery loop to start
  - Go back to the best route for exp

**Comment by iIoli** [comment]
uhh ok let me see if I can reproduce it

**Comment by iIoli** [comment]
[[v0.10.9] PokeClicker 2023-02-04 17_09_29.txt](https://github.com/Farigh/pokeclicker-automation/files/10609183/v0.10.9.PokeClicker.2023-02-04.17_09_29.txt)
So after the dungeon quest was completed, the script just idled at the dungeon entrance instead of going to the best route for xp

**Comment by Farigh** [comment]
Nice catch !

This should properly now 😉
