### ISSUE TITLE
Dungeon: Stop Auto Fight after 500 clears

### ISSUE THREAD

**Issue by BaqFish** [Farigh/pokeclicker-automation#250]
While trying to clear all achievements in the later regions the cost for the dungeons is very high. When on accident I leave the Auto Fight going in a dungeon for too long I've ended up clearing a dungeon for 1000+ times, instead of just the 500 that I need.

I would love an option to toggle below "Skip chests pickup" and "Skip the boss fight" that's called "Stop in 500 Clears". Possibly even a number you could set yourself, if you want to try to grab all Resistances in a dungeon without having to let it run forever. But even fixed at 500 would be fine.

From what I understand "Focus on: Achievements" does something similar, but it prevents me from doing other tasks while at it, which leads me to not using the Focus feature in this game.

Thanks in general for the Automations. I would have definitely quit the game without 'em.

**Comment by Farigh** [comment]
> While trying to clear all achievements in the later regions the cost for the dungeons is very high. When on accident I leave the Auto Fight going in a dungeon for too long I've ended up clearing a dungeon for 1000+ times, instead of just the 500 that I need.
> 
> I would love an option to toggle below "Skip chests pickup" and "Skip the boss fight" that's called "Stop in 500 Clears". Possibly even a number you could set yourself, if you want to try to grab all Resistances in a dungeon without having to let it run forever. But even fixed at 500 would be fine.
> 
> From what I understand "Focus on: Achievements" does something similar, but it prevents me from doing other tasks while at it, which leads me to not using the Focus feature in this game.

This should indeed be a `Focus on Achievements` only feature. It's planned to add a more tweakable selection of tasks via #97
I don't really understand the need you are describing.
If you are in a dungeon, what would you like to do, that the game would let you do ?

> Thanks in general for the Automations. I would have definitely quit the game without 'em.

Thanks, I'm glad you like it :)

**Comment by BaqFish** [comment]
Thanks for the quick response. 

I guess it boils down to not want to be "forced" to do a specific task as is the case with "Focus on". It doesn't allow me to go around other maps and just do smaller activities. So like Hatchery/Mining/Farming/Auto Shop I enjoy the background help that I get from it, while still mixing up different tasks.

**Comment by Farigh** [comment]
You can turn off this feature when you want to do other things.
My point was that the game does not let you do anything while in a dungeon anyway.
(And as specified on the home page, I will never implement something that the game would not allow you to do)

**Comment by BaqFish** [comment]
Ya, it's about in-between dungeon runs. But as you said I can turn off the feature if I want to do other things. And if thats a feature that will be improved upon with #97 then that answered this issue. Thanks again!
