### ISSUE TITLE
After unlocking Pokerus, Focus on Quests doesn't work with catch quests.

### ISSUE THREAD

**Issue by bUrself1** [Farigh/pokeclicker-automation#255]
Focus on Quests doesn't select a ball to catch Pokemon that are contagious with Pokerus so nothing ends up getting caught because all my Pokemon are contagious. I assume if I were to get everyone to EV 50 this would fix itself but that would take a while :)
![image](https://user-images.githubusercontent.com/124647052/217136657-87c04ce7-8511-413d-826f-206f3fec6786.png)

Here is a save if needed.
[[v0.10.9] PokeClicker 2023-02-07 02 57 08.txt](https://github.com/Farigh/pokeclicker-automation/files/10671124/v0.10.9.PokeClicker.2023-02-07.02.57.08.txt)

**Comment by Farigh** [comment]
I did not think about this side effect when the feature got introduced 😮 

It should now work properly
