### ISSUE TITLE
Water gem automation sends you to magikarp jump

### ISSUE THREAD

**Issue by iIoli** [Farigh/pokeclicker-automation#260]
<img width="1008" alt="Screenshot 2023-02-14 at 3 56 20 PM" src="https://user-images.githubusercontent.com/63279082/218673946-78d93eeb-95ed-415b-95e8-c7145f3dd6ce.png">
real

**Comment by Farigh** [comment]
I'll look into it when I got time.
Could you provide a save reproducing this, so I can check my work once done ?

**Comment by iIoli** [comment]
[[v0.10.9] PokeClicker 2023-02-15 11_39_04.txt](https://github.com/Farigh/pokeclicker-automation/files/10742440/v0.10.9.PokeClicker.2023-02-15.11_39_04.txt)
Sure. Here it is.

**Comment by Farigh** [comment]
Thanks for the save, the problem should now be fixed
