### ISSUE TITLE
Hatchery: Prioritize pokémon from the following category

### ISSUE THREAD

**Issue by BaqFish** [Farigh/pokeclicker-automation#270]
### Is your feature request related to a problem? Please describe.
I like to have different Categories for different groups of Pokémon which I switch focus on from time to time. Mostly simple things like "Team" and "Magicarps". If I want to breed a specific Category I have to change the order of the Category around and even then I can not define by which order the individual Pokémon within the group are being bred. 

### Describe the solution you'd like
Below the setting "Sorting on attribute" could be another setting called "Prioritize pokémon from the following category" where all the users categories are listed. If that is selected that category is used first and sorted by the previous setting. If there are no further Pokémon to breed in that category it should revert back to the current behaviour and breed whatever is next based on the sorting.
![image](https://user-images.githubusercontent.com/1365432/221308281-8007d188-7962-4ee3-ab80-e641941e3ea2.png)
The actual situation that made me ask for this is that I'm trying to have my "Team" category all with the same attack, so I'd like to filter on that category but sort them by attack for breeding.

I think this would feel like a native extension to how the prioritizing system already works, though I'm not sure how complicated it is to display all the categories the user created, especially if those are being changed in the actual game after being selected as a priority.

Thanks again for the work on this addon!

**Comment by Farigh** [comment]
I'll see what can be done.
However, since this need is a pretty niche, don't expect it to be implemented in priority.

Feel free to contribute, BTW.
