### ISSUE TITLE
Farm: strange farming strategy

### ISSUE THREAD

**Issue by jensver** [Farigh/pokeclicker-automation#276]
The only berries left to unlock are Lansat and Enigma.
After two cycles of the correct Roseli planting strategy, I see that the automation is trying this:
<img width="948" alt="Screenshot 2023-03-02 at 09 58 21" src="https://user-images.githubusercontent.com/40829647/222659881-d747b528-90ab-46c5-b1ac-b0cc3e6906e5.png">

I can't find in the code why it's doing this.
Bug or do I miss something? :)

**Comment by Farigh** [comment]
Hi, 
Could you provide a save so I can check what might have happened ?

**Comment by jensver** [comment]
[[v0.10.9] PokeClicker 2023-03-03 09_01_06.txt](https://github.com/Farigh/pokeclicker-automation/files/10880283/v0.10.9.PokeClicker.2023-03-03.09_01_06.txt)

**Comment by jensver** [comment]
Nevermind, I had an epiphany :)
Starf and Lansat has almost identical farming strategies.
It's just mutation on Roseli :)
