### ISSUE TITLE
Hatchery doesn't focus on subsequent mega evolution attack requirements in Real Evolutions challenge.

### ISSUE THREAD

**Issue by cfedey** [Farigh/pokeclicker-automation#283]
### Describe the bug
This is only applicable to the Real Evolutions challenge.

Currently, with the "Focus on mega evolution requirements unlock" toggle enabled in the Hatchery settings, the script will breed the required attacks for those that need it, the first time around.

However, once a mega evolution is obtained, and a new prerequisite form is obtained, the hatchery ignores it for purposes of reaching the attack requirement again for subsequent evolutions. 

I believe the hatchery should go through and get these attack requirements again, so EVs can be accumulated on mega evolutions. This process would only need to be done twice, as the prerequisite form isn't lost on subsequent evolutions like it is the first time around.

### Steps to Reproduce
1. Set hatchery to focus on mega evolution requirements.
2. Wait for all attack requirements to be met.
3. Mega evolve.
4. Obtain replacement prerequisite form.
5. Hatchery ignores the new prerequisite form.

### Expected behavior
Expected behavior would be for it to continue focusing on the mega evolution requirements, as once the prerequisite form is consumed for the mega evolution, the requirement is no longer met and must be met again.

### Additional context
Not sure why, but it might have been focusing on a second round of attack requirements for a short time. I have a few prerequisite forms that have inflated attack, even after the mega form has been obtained. Maybe it did start working on the second round of attack requirements but stopped when all of the remaining first round requirements were met and it thought it was done?

**Comment by MatPietrzyk** [comment]
Seems like this actually was the intended behaviour, but then it was changed at someone's request to NOT breed mega evolutions again in the real evolutions challenge. The change is posted here:
https://github.com/Farigh/pokeclicker-automation/commit/a0db7196b6a48650361ff5ad772bf5aa5cf9025b
Could warrant a toggle, or just going back to your solution, because it is better for long-term playing and doesn't require much chnage.

**Comment by cfedey** [comment]
Thanks for the reply. I don't think I could learn how to code within the week, so I'll leave it to the expert. I'm using the above workaround for now, so no rush.

**Comment by Farigh** [comment]
@cfedey I added the setting, it should work properly, however I only did some basic tests forging a save from my regular one, so I might have missed something.

Don't hesitate to open an issue in such case.

**Comment by cfedey** [comment]
Thanks for the update. I did some tests as well, and it seems to be working as expected. If I notice anything out of the ordinary I'll post about it. Thanks again.
