### ISSUE TITLE
Blaze Cassette automatically unequips

### ISSUE THREAD

**Issue by josepbernal23** [Farigh/pokeclicker-automation#287]
Blaze Cassette automatically unequips, I don't know why it happens

![image](https://user-images.githubusercontent.com/55711055/229643492-b759d465-e1b4-482e-ad87-a3dfe144dc15.png)
a few seconds later...
![image](https://user-images.githubusercontent.com/55711055/229643572-f04c6988-99ce-4da8-98a4-9cd11e17cfc7.png)

**Comment by jensver** [comment]
Probably because of the setting in the farming setup: 'update oak item loadout when needed'
