### ISSUE TITLE
Add minimum price to shop tab?

### ISSUE THREAD

**Issue by TheSaucyWelshman** [Farigh/pokeclicker-automation#288]
It would be nice to have the minimum price of each item in the auto shop tab so I don't need to hit up the wiki when changing shop requirements. Maybe hovering over the "coin" at the end of the row could display it?

**Comment by Farigh** [comment]
Sorry for the late reply, I've been a bit occupied lately.

Setting any value under the minimum price in the `max base value` field will automatically reset its value to the minimum price.
I don't think much more is needed.
