### ISSUE TITLE
Focus.PokérusCure - not working since update (in dungeons)

### ISSUE THREAD

**Issue by jensver** [Farigh/pokeclicker-automation#298]
After reloading Pokeclicker since the update, the pokérus cure automation did the routes that had non-resistant poke.
But now that all routes are back to resistant state, he is not starting the dungeon clearing for non-resistant poke.
Save file in attachement!
[[v0.10.11] PokeClicker 2023-05-08 09_07_27.txt](https://github.com/Farigh/pokeclicker-automation/files/11419707/v0.10.11.PokeClicker.2023-05-08.09_07_27.txt)

**Comment by jensver** [comment]
i18next::translator: missingKey en settings pokeballFilterPokerus Pokérus State.   i18next.js:53 

This message is in the console when you click the on button when pokerus is selected in the focus box.

**Comment by Farigh** [comment]
Hi,

I'll take a look at it in the coming days.
I'm a bit busy for now

> i18next::translator: missingKey en settings pokeballFilterPokerus Pokérus State. i18next.js:53
> 
> This message is in the console when you click the on button when pokerus is selected in the focus box.

This is a pokeclicker warning, tide to missing translation data, it occurs often and is not relevant for the automation.

**Comment by Farigh** [comment]
The problem should be fixed now, thanks for the save it greatly helped 👍

**Comment by jensver** [comment]
> The problem should be fixed now, thanks for the save it greatly helped 😉

Works as a charm.
Thanks for the continued development and quick response here :)
