### ISSUE TITLE
Catch filters set by automation are in wrong order for ideal/expected use

### ISSUE THREAD

**Issue by Lokilotus** [Farigh/pokeclicker-automation#303]
### Describe the bug
Catch filters set by automation are in wrong order for ideal/expected use.

### Steps to Reproduce
1. Reorder catch filters while automation is off to "Caught, Automation, Caught Shiny, New, New Shiny", going down the list.
2. As expected, the lowest filter is used, e.g. New Shinies always are caught with a Master Ball.
3. Turn on automation and let it reorder the filters.
4. Now no shinies, new or otherwise, will be caught, unless the automation wants them to be; in addition this breaks the flow of quests that ask for shinies to be caught while other quests are ongoing (will try to catch them, but not with any guarantee unlike setting the shiny filter to a Master Ball) as the automation makes the shiny quest the lowest priority quest to complete from what I can tell.

### Expected behavior
The more specific a filter is, the lower down it should be by default - i.e. New Shinies, then New (or Caught Shinies), then Caught Shinies (or New), then either the automation or caught, depending on preference.

### Additional context
Would be resolved by implementing feature described in https://github.com/Farigh/pokeclicker-automation/issues/295#issue-1699067385.

**Comment by Farigh** [comment]
Hi, 

The implementation of #295 will only skip the `Automation`filter from being moved last, if it's not.

For now, if you reorder your filters, only the automation one should be moved last (so it can have priority, as you rightly said) and your filter's order should be kept as-is.

Did you experiment another behavior ? If so, which browser are you using so I can try to figure out what happens.

**Comment by Lokilotus** [comment]
Setting the order of the filters, automation turned off:
![image](https://github.com/Farigh/pokeclicker-automation/assets/2342253/f6b41636-324d-4052-824a-b53874b52208)

After turning automation on: no change. HOWEVER, Adjusting automation to be at the top:
![image](https://github.com/Farigh/pokeclicker-automation/assets/2342253/cfd5d0c9-130e-42cb-b8e6-bc4f3bc150a5)

...something screwy is going on. I was going to show a screenshot of how just moments later the order in the modal gets screwed up but the side panel stays the same, and how that causes very screwy behaviour, but for some unknown reason now Automation is staying at the top and OHHHHH (epiphany, yes I am writing this as I experiment) - Automation has to be turned ON to edit the ordering, and as I usually sit in quest mode I had no quests that needed the automation - but going to dungeon tokens mode caused the issue:
![image](https://github.com/Farigh/pokeclicker-automation/assets/2342253/8936f5ff-d7a2-4fcd-8860-6b2389dc2ee6)

After swapping the bottom two (caught and automation) and then unswapping them so Automation was again second last:
![image](https://github.com/Farigh/pokeclicker-automation/assets/2342253/f5f3c307-b575-47c3-8ba3-604694318212)

As you can see, something weird is going on.

I play on Chrome, and am not running with any other addons.

**Comment by jensver** [comment]
@Lokilotus have tried resetting the filters in stead of reordering?
I had some strange behavior after the new catch filters update, but after resetting the filters it was fixed.

**Comment by Farigh** [comment]
@Lokilotus I did not manage to reproduce your behaviour.
I tried many configurations : 
  - Firefox 113.0.2 (64 bits)
  - Chrome 113.0.5672.127 (Build officiel) (64 bits)
  - Pokeclicker app
  
I couldn't reproduce on any of those.

Did jensver's tip solve your issue ?

**Comment by biomagnet** [comment]
Not to bring up old topics, but I definitely cannot move the Automation filter. It just makes itself top priority every time I tell it to Focus On something, like Dungeon Tokens. It made me miss my first Thundurus by not using my Master Ball. :(
