### ISSUE TITLE
Dungeon clearing broken on Go to the next floor

### ISSUE THREAD

**Issue by jensver** [Farigh/pokeclicker-automation#305]
After updating to the latest version 
Save file in attachment!

[%5Bv%7Bversion%7D%5D%20PokeClicker%20%7Bdate%7D.txt](https://github.com/Farigh/pokeclicker-automation/files/11931199/5Bv.7Bversion.7D.5D.20PokeClicker.20.7Bdate.7D.txt)

**Comment by Essoheli** [comment]
Having the same issue. Checked console, seeing:

Uncaught TypeError: DungeonRunner.handleClick is not a function
    __internal__dungeonFightLoop https://www.pokeclicker.com/ line 92 > injectedScript:390

**Comment by Farigh** [comment]
Sorry for the delay, I've been a bit busy lately.

It should work properly now
