### ISSUE TITLE
Exp Share Oak item it's doesn't equiped when the quest is active

### ISSUE THREAD

**Issue by DiegoVeintisiete** [Farigh/pokeclicker-automation#33]
When the AutoQuest featured is on and the "Equip the exp share and defeat xxx pokemon" Quest is active, the Item is not equipped.

Looking into the code, I noticed you are using 4 slots of OAK items, and the game can handle only 3 without any other script active.

![image](https://user-images.githubusercontent.com/108158870/175749206-01984c32-d203-4774-851d-caecb4ec852e.png)

Regards

**Comment by Farigh** [comment]
Hi,

The listing in the code has 4 items but it should not be a problem, indeed the script always prepend the needed Item: 
https://github.com/Farigh/pokeclicker-automation/blob/0859d57cbccfe0f14b5ce3a508cd208ae8135bfe/src/lib/Focus/Quests.js#L773-L777

Something should have gone wrong elsewhere; 
I reproduced, I'll look into it
