### ISSUE TITLE
Add a new advanced settings to dungeon

### ISSUE THREAD

**Issue by 0tobi** [Farigh/pokeclicker-automation#330]
So I was thinking about something that could be nice (idk if useful) but why not a input to tell how many time we want to do the dungeon we are in?

Like if i want to do 1000 times the viridian forest i will just have to put the amount and let the auto dungeon go

**Comment by Farigh** [comment]
Hi, could you describe the need for such feature ?

I fill like their are only 2 use-case : 
  - either run while idle => no need for a timer, you can disable the feature once you come back to the game
  - Or try to unlock achievements => the `Focus on Achievement` feature is made for this case.

**Comment by 0tobi** [comment]
> Hi, could you describe the need for such feature ?
> 
> I feel like their are only 2 use-cases :
> 
> * either run while idle => no need for a timer, you can disable the feature once you come back to the game
> * Or try to unlock achievements => the `Focus on Achievement` feature is made for this case.

Oh yeah I forgot about the achievements thing
