### ISSUE TITLE
Missing Context Menus

### ISSUE THREAD

**Issue by Leonidas2306** [Farigh/pokeclicker-automation#333]
None of the Context menus are showing up for me, except the Safari Zone one. (Cannot test for the Battle Cafe, as I am not at that point yet thou).

As i only started using the script post V0.10.18, I don't know wether this maybe a known Issue, but couldn't find any report about it.

Tested in browser via Tempermonkey and on the deskzop app.

**Comment by Farigh** [comment]
This is a side-effect of #332

**Comment by Farigh** [comment]
The script-suite should now work properly.
Don't hesitate to reopen this issue or create a new one if any other issues appear.
