### ISSUE TITLE
Battle Frontier is not triggered by quests

### ISSUE THREAD

**Issue by timewaster** [Farigh/pokeclicker-automation#335]
When a quest goal involves the battle frontier the automation does not attempt to start the battle frontier leading to lingering goals that prevent further automation.

**Comment by timewaster** [comment]
If turning on quest automation within the battle frontier this then seems to fall back to a fail safe behavior of a route that is cleared quickly.

**Comment by Farigh** [comment]
Thanks for the issue.

This was another v0.10.18 regression.
It should be fixed and work properly again
