### ISSUE TITLE
Pokebal filters priority 

### ISSUE THREAD

**Issue by jefetotal** [Farigh/pokeclicker-automation#337]
### Describe the bug
The priority created by the scrip stays at the bottom, the place with lower priority, making it not work.
While there is an option to change the priority to be bottom to top, it might be nice to change it so it works with default settings. 

### Expected behavior
I would expect it to be in the top, where is higher priority by default.

### Additional context
Im playing in browser v0.10.19

**Comment by Farigh** [comment]
The update did indeed add a setting to change the display order : 
![image](https://github.com/Farigh/pokeclicker-automation/assets/11090416/160b7a65-6b15-46b5-a8fd-0ad721690c3e)

I'll take a look at it and try to fix it quickly.
In the meantime, I'd suggest to check this setting

**Comment by Farigh** [comment]
This should now work properly
