### ISSUE TITLE
Automation Inverts all manual Pokeball Filters

### ISSUE THREAD

**Issue by lmikulla** [Farigh/pokeclicker-automation#339]
https://github.com/Farigh/pokeclicker-automation/blob/e60b72800f3c6fd61b174764b45b285f7b93c554/src/lib/Utils/Pokeball.js#L183

Properties enabled and inverted are ko.observable, this line overwrites them with a (truthy) function, which inverts all user set manual filters. This results in unexpected behavior of the Users pokeball Filters

**Comment by Farigh** [comment]
ho, I missed those two ....
Thanks for the issue, I'll fix this right away

**Comment by Farigh** [comment]
It should work properly now.
Sorry for the inconvenience
