### ISSUE TITLE
Orre automation

### ISSUE THREAD

**Issue by MatPietrzyk** [Farigh/pokeclicker-automation#355]
Focus on achievements and on pokerus doesn't go on to Orre and instead goes to further regions despite already clearing regions prior to that in terms of achievements and EV's. Is Orre region placed after Galar in priority list or is this an unintended bug?
Savefile in attachment.
[[v0.10.19] PokeClicker 2024-03-25 15_58_44.txt](https://github.com/Farigh/pokeclicker-automation/files/14746378/v0.10.19.PokeClicker.2024-03-25.15_58_44.txt)

**Comment by Farigh** [comment]
Your problem looks similar to the one from the #354 discussion.

Thanks for providing a save file, I'll take a look

**Comment by Farigh** [comment]
This should nos work as expected.

The Orre sub-region is now considered the same difficulty as the Sinnoh one
