### ISSUE TITLE
Dungeon: Select minimum Chest Rarity

### ISSUE THREAD

**Issue by TheGiriel** [Farigh/pokeclicker-automation#357]
### Is your feature request related to a problem? Please describe.
This is not a problem in itself, opening _all_ chests simply doesn't help much and it'll inflate boss HP (See add. context).

### Describe the solution you'd like
Add an option to select which type of chest (and up) to loot. Like how you can select the Pokéball to use for the boss, there could be an option to select which chests to pick up (Normal, Rare, Epic, Legendary, Mythic). Epic and up usually have more important contents (e.g. atk-boosting Held Items being are in Legendary chests).

### Additional context
Most Normal or Rare chests become useless as you'll gather so many battle items that the effects will run for weeks after one region's worth of dungeons and the automation suite already has the Auto Shop that allows for those items to be bought automatically. Furthermore, each opened chest increases the boss HP by 20%, which can slow down dungeon clearing/farming.

**Comment by Farigh** [comment]
Great idea, you can now use the new drop-down list for this : 
![image](https://github.com/Farigh/pokeclicker-automation/assets/11090416/e0b0bc93-b313-49d2-b648-7b10fc13e5b3)
