### ISSUE TITLE
Focus Quest do not clear type filter before trying to cach shadow pokemon

### ISSUE THREAD

**Issue by Mendez63** [Farigh/pokeclicker-automation#371]
### Describe the bug
So sometime when using focus quest, it start a loop trying to catch shadow pokemon but with a type filter still on, so if no pokemon match the type filter, it's stuck. My clue is the script launch a type restricted catch quest and a shadow catch quest at the same time, do the first then switch to the second without removing the filter

### Steps to Reproduce
-Find a catch type restricted quest and a shadow catch quest together
-Let the Focus on Quest script work

### Expected behavior
The script need to clear the filter after a type restricted quest (or before starting a shadow one)

### Additional context
Same on both desktop and website

![Capture d'écran 2024-07-03 213703](https://github.com/Farigh/pokeclicker-automation/assets/172088058/e67517d1-788e-4008-bb70-5ec50265aeae)

**Comment by Farigh** [comment]
Thanks for the report, it should now work as intended
