### ISSUE TITLE
Keep shiny charm on

### ISSUE THREAD

**Issue by andrewfishman** [Farigh/pokeclicker-automation#380]
The "Optimize Oak item layout" is great, but I'd love the option to have the shiny charm always on if I'm on a route where shinies are available.  I obviously don't need it when farming gyms or the battle frontier, but if I'm just idling on a route, I would always prefer that the shiny charm be equipped.

**Comment by andrewfishman** [comment]
Never mind, I think I just misunderstood how the function works.  Sorry, I'm not able to delete the thread myself.

**Comment by Farigh** [comment]
You can't remove issues, I'll close it and add the right tag
