### ISSUE TITLE
[Bug] Haina Desert (Alola) is missing from the Trivia > Fast Travel menu.

### ISSUE THREAD

**Issue by TDarkShadow** [Farigh/pokeclicker-automation#382]
### Describe the bug
> A clear and concise description of what the bug is.  

The zone Haina Desert from the worldzone Alola is missing from the Trivia > Fast Travel menu.

### Steps to Reproduce
> Steps to reproduce the behavior:  

1. Go to the Alola worldzone, Ula'ula Island subregion, and defeat atleast 10 pokemon on Alola Route 13.
1a. It might be necessary to beat the Champion first. I only discovered this bug after reaching Galar region.
3. Try to fast travel to 'Haina Desert' via the Trivia > Fast Travel menu.

### Expected behavior
> A clear and concise description of what you expected to happen.  

Haina Desert should be one of the possible fast travel zones / points in the menu.

### Additional context
> Add any other context about the problem here (OS, Browser, Screenshots, game save file...).
Windows, using the Pokeclicker desktop application (Electron?).
![image](https://github.com/user-attachments/assets/b8674255-ea8c-41fc-a96d-27d8e69311b7)

**Comment by jensver** [comment]
Haina Desert is a route, you can't fast travel to routes.

**Comment by TDarkShadow** [comment]
Ah right, my mistake. Thanks for the quick feedback.
