### ISSUE TITLE
Magic Ball not selected for quests/focus on that involve catching pokemon

### ISSUE THREAD

**Issue by tatsumasa314** [Farigh/pokeclicker-automation#39]
### Describe the bug
So far I have seen this for the catch 1 shiny Pokemon quest as well as the focus on dungeon tokens. I would expect that enabling the Magic ball would make sense for those since it increases your catch chance but it doesn't seem to equip in either scenario. There may be others!

### Steps to Reproduce
1. Start dungeon token focus
2. Observe that the magic ball is not one of the items selected

### Expected behavior
Magic ball to be an item selected for quests/focuses that involve catching pokemon

**Comment by Farigh** [comment]
The oak item were initially only used by the Quests focus topic (which was a dedicated feature, with it's own button).
I reused this mechanics for the Achievement one, which was pretty clause.

I did not think about setting an oak item loadout for other topics, I'll consider it :)

**Comment by Farigh** [comment]
I did the necessary changes in the PR #39.

However, about the Magic ball not being selected while running the `Focus on Dungeon Token`. I could not reproduce, this is already the case.
I unequipped all my oak items and it did equip the `Magic ball`. I also tried equipping a full loadout without the `Magic ball` and it did equip it as expected.

What might have happened in your case is: if you don't have enough Ultraballs, the automation will try to buy some.
If you don't have enough money to buy at least 10 Ultraballs (around 20.000 pokedollars) then the automation will farm some money to buy some (moving you to the most efficient Gym or route to earn money).

If it's not your case, can you provide some additional information ?

**Comment by Farigh** [comment]
The catch a shiny case was definitely a bug, it's been fixed by #39
