### ISSUE TITLE
Add an option to buy items automatically when under a certain threshold

### ISSUE THREAD

**Issue by Farigh** [Farigh/pokeclicker-automation#45]
### Is your feature request related to a problem? Please describe.
It would be nice to be able to set a threshold for some recrurent items that the automation would automatically by when at the lowest cost.

### Describe the solution you'd like
I'd like the following items to be auto-buyable:
  - Ultraball
  - xAttack
  - xClick
  - Lucky_egg
  - Token_collector
  - Item_magnet
  - Lucky_incense

A new menu should be created to avoid overloading the actual one that should stay as minimalist  as possible.

### Additional context
Suggested in #43

**Comment by Farigh** [comment]
Here is the code I use from time to time: 
```javascript
watcher = setInterval(function()
{
    if (ItemList["Ultraball"].totalPrice(1) === ItemList["Ultraball"].basePrice)
    {
        ItemList["Ultraball"].buy(100);
    }
    if (ItemList["xAttack"].totalPrice(1) === ItemList["xAttack"].basePrice)
    {
        ItemList["xAttack"].buy(100);
    }
    if (ItemList["xClick"].totalPrice(1) === ItemList["xClick"].basePrice)
    {
        ItemList["xClick"].buy(100);
    }
    if (ItemList["Lucky_egg"].totalPrice(1) === ItemList["Lucky_egg"].basePrice)
    {
        ItemList["Lucky_egg"].buy(100);
    }
    if (ItemList["Token_collector"].totalPrice(1) === ItemList["Token_collector"].basePrice)
    {
        ItemList["Token_collector"].buy(100);
    }
    if (ItemList["Item_magnet"].totalPrice(1) === ItemList["Item_magnet"].basePrice)
    {
        ItemList["Item_magnet"].buy(100);
    }
    if (ItemList["Lucky_incense"].totalPrice(1) === ItemList["Lucky_incense"].basePrice)
    {
        ItemList["Lucky_incense"].buy(100);
    }
}, 5000);
```

And to stop the loop : 
```javascript 
clearInterval(watcher);
```

**Comment by oohwooh** [comment]
now that Item Magnets have been renamed to Dowsing Machines, the script you posted needs to be modified as such: 

```js
watcher = setInterval(function()
{
    if (ItemList["Ultraball"].totalPrice(1) === ItemList["Ultraball"].basePrice)
    {
        ItemList["Ultraball"].buy(100);
    }
    if (ItemList["xAttack"].totalPrice(1) === ItemList["xAttack"].basePrice)
    {
        ItemList["xAttack"].buy(100);
    }
    if (ItemList["xClick"].totalPrice(1) === ItemList["xClick"].basePrice)
    {
        ItemList["xClick"].buy(100);
    }
    if (ItemList["Lucky_egg"].totalPrice(1) === ItemList["Lucky_egg"].basePrice)
    {
        ItemList["Lucky_egg"].buy(100);
    }
    if (ItemList["Token_collector"].totalPrice(1) === ItemList["Token_collector"].basePrice)
    {
        ItemList["Token_collector"].buy(100);
    }
    if (ItemList["Dowsing_machine"].totalPrice(1) === ItemList["Dowsing_machine"].basePrice)
    {
        ItemList["Dowsing_machine"].buy(100);
    }
    if (ItemList["Lucky_incense"].totalPrice(1) === ItemList["Lucky_incense"].basePrice)
    {
        ItemList["Lucky_incense"].buy(100);
    }
}, 5000);
```

if implemented into the script, it would make sense to create a config object that stores what items should be automatically purchased, and a limit for when it shouldn't buy, even if the price is low. That also enables you to iterate over that object in a loop, and trim down the large amount of duplicate code in your posted script.

**Comment by Farigh** [comment]
The script was just an example of what I did in a rush a while ago when I needed It.

As stated in the description when implemented it should be in a dedicated menu to expose all the possible items to buy, with the amount to buy and a threshold under which it should be

**Comment by oohwooh** [comment]
Makes sense - I'm happy to work on this in a pull request if you'd like.

**Comment by Farigh** [comment]
Why not :) 

I still have to figure out the best way to add setting-menus for this change and other issues though

**Comment by oohwooh** [comment]
I think a good system would be one where more advanced settings could be injected into game modals - for instance for this one, there could be extra buttons added in the poke mart, for toggling autobuy and configuring the limit. That would save from having to use an unwieldy dropdown. This could be expanded to other areas of the game as well, for instance hatchery options could be moved into the hatchery modal, etc. 

I still think there is value in having a convenient sidebar for toggles, but as the script grows it will get very cluttered fast

**Comment by Farigh** [comment]
I'll dig into the menu part tomorrow
