### ISSUE TITLE
Use chisel instead of bombs for automatic mining

### ISSUE THREAD

**Issue by oohwooh** [Farigh/pokeclicker-automation#50]
### Is your feature request related to a problem? Please describe.
Using the bomb at the start of a new layer, while easy to implement, is a lot less efficient than systematically using the chisel. This is especially apparent on layers without many items, or if it contains something small like a heart scale.

### Describe the solution you'd like
I think it would be best to use an efficient mining pattern like the one outlined [here](https://pokeclicker.miraheze.org/wiki/Underground#Efficiency) - you could also prioritize tiles that can be mined in only 1 use of the chisel, as these are better to clear first under the assumption that all tiles mined in this method have an equal probability of containing a treasure.

**Comment by linkdest** [comment]
I suggest using [this priority order](https://i.imgur.com/7obFxyK.png) instead the one linked in the wiki.

**Comment by Farigh** [comment]
After putting some thought into this, I think we should still use the bomb but with more conditions.

Maybe only use it if the board has at least a certain % of the tiles covered.
We should consider the bomb efficiency as well to set such percentage (as the bomb can be upgraded).

I think we can come up with a solution similar to the one implemented for the hammer through the PR #95

**Comment by Farigh** [comment]
I'm closing this issue, since the v0.10.23 will require a full revamp of the approach
