### ISSUE TITLE
Switch to mining oak items before clearing tiles

### ISSUE THREAD

**Issue by oohwooh** [Farigh/pokeclicker-automation#51]
### Is your feature request related to a problem? Please describe.
Right now, if I want to level up or gain the bonus from the mining oak items, I need to use up precious slots on items that (barring the battery) provide no buff being active when mining is not happening.

### Describe the solution you'd like
I think the easiest solution would be to, every time a mining operation is about to occur, quickly:
* save the state of current oak items
* equip the Cell Battery, Explosive Charge, and Treasure Scanner (provided they are unlocked)
* Mine the tiles
* return to the saved state of oak items

### Additional context
I am not sure the performance impact this change would have on the script, as it does significantly increase the number of actions taken every mining loop. If it does turn out to have a significant performance impact, I think the interval delay can be increased, ~~as 0.3 seconds is rather often for something that only changes state (without upgrades) once a minute.~~ 

edit as I just realized I misunderstood the code

**Comment by Farigh** [comment]
Because of the other focus features setting the loadout, this should probably be restricted to the diamond focus feature (#62)

**Comment by Farigh** [comment]
I'm closing this issue, since the v0.10.23 will require a full revamp of the approach
