### ISSUE TITLE
Auto Achievement failed if the gym is not ready

### ISSUE THREAD

**Issue by akwawa** [Farigh/pokeclicker-automation#56]
### Description of the bug
If you choose to focus on the achievement and the gym is not available, the script does not change the achievement to look for another one to complete.

### Steps to reproduce the bug
1. Requirements: Have a locked gym and an unlocked one or an unlocked dungeon.
2. The achievement must be focused on the locked gym.
3. The script does not change focus and stops.

### Expected behavior
The script should look for another achievement to be done.

### Additional context
If all achievements are completed and the gym is still blocked, we will see at that time but I don't think it is possible.
A backup with the problem is attached to this issue.

[[v0.9.7] PokeClickerSave_2022-06-30 15_30_03.txt](https://github.com/Farigh/pokeclicker-automation/files/9021316/v0.9.7.PokeClickerSave_2022-06-30.15_30_03.txt)

**Comment by Farigh** [comment]
Hum, this is still a bug involving different behavior between Firefox and Chrome ...
I'll look into it tomorrow
