### ISSUE TITLE
Focus on Diamonds

### ISSUE THREAD

**Issue by Nox-Ater** [Farigh/pokeclicker-automation#62]
You could implement a mode where you buy a certain number of restore potions and focus on mining until you run out of potions or something similar.
Sometimes it is necessary to get gems.

**Comment by Farigh** [comment]
Hi, 
Do you mean to get diamond ?
If that's the case, I sure would do something about it, not sure if mining is the best approach to get some though.

**Comment by Nox-Ater** [comment]
Yes, diamonds. Mining is the only way to get diamonds.

**Comment by Farigh** [comment]
Actually their are a fiew dungeons that rewards underground items, like`Rock tunnel` for example.

I don't know which solution would be the most efficient way

**Comment by Nox-Ater** [comment]
Even so I think it would be a good option to have a way to be able to advance quickly in Underground

**Comment by FireGolem321** [comment]
With this, it might be a good feature if Survey can be done when entering a new layer and if the diamond value is below the predetermined amount, it skips that layer. You could also have it focus on plates, evolution items, or fossils.

**Comment by Farigh** [comment]
Once the main mode is implemented, that could be good improvements indeed :)

**Comment by Farigh** [comment]
Suggestion: Allow buy and use of small restore at all time instead of only for mining quests

**Comment by Farigh** [comment]
Focus on Diamond does not seem needed since #128 was pushed
