### ISSUE TITLE
Hatchery Upgrade: Allow for PokeRus priority

### ISSUE THREAD

**Issue by Essoheli** [Farigh/pokeclicker-automation#63]
The PokeRus can only be spread by the chosen Kanto starter(at least at current), it would be nice to have the option to have the auto-hatchery place this one in the hatchery and spread the PokeRus around to the rest of your pokemon, prioritising hatching those that are still uninfected while the starter's egg is not ready to hatch.

**Comment by Farigh** [comment]
I'll look into it, I did not much time learning the new mechanics the 9.6.0 upgrade implemented.

That sounds a really critical point to overcome the exp gain nerf.

I'll try to add it in the coming days :)

**Comment by oohwooh** [comment]
It looks like there were just some changes made to pokerus in [this commit](https://github.com/pokeclicker/pokeclicker/commit/0f43c5de868da7f8fda85600c78dec719866a117) - from the glance I took at it, it seems pokerus now spreads between two Pokemon who share a type in common.

Probably not worth putting much dev effort into this until the reworked system is released.
