### ISSUE TITLE
When out of money and balls

### ISSUE THREAD

**Issue by Fyuri13** [Farigh/pokeclicker-automation#67]
### Steps to Reproduce
When Focus on is set to Quests and turned on, if you run out of Ultra Balls and Money, the script tries to change locations to gain money and move to complete quests at the same time so it doesn't capture anything and gets stuck. In my game it tries to move to a gym to gain money and it doesn't complete the gym so no money.

### Expected behavior
stay in the location needed to gain money for Ultra Balls

**Comment by Farigh** [comment]
I reproduced by removing all pokemon from my save, I'm looking into it.

**Comment by Fyuri13** [comment]
Thank You, I knew i didnt make it up lol
