### ISSUE TITLE
Dungeon Boss Priority

### ISSUE THREAD

**Issue by Fyuri13** [Farigh/pokeclicker-automation#73]
### Is your feature request related to a problem? Auto dungeon takes too long to complete
When you're in it for the long haul, and play with all challenges on, it can take a VERY long time for the Dungeon Fight  to be able to complete a full dungeon

### Describe the solution you'd like
Please implement a boss priority option for Dungeon Fight

**Comment by Farigh** [comment]
I'm not sure to understand what you're requesting.
How does it defer from the [Complete as soon as the boss was found](https://github.com/Farigh/pokeclicker-automation/wiki/Menu-presentation#large_blue_diamond-the-dungeon-fight-advanced-settings) advanced setting ?

**Comment by Farigh** [comment]
No problem, I added it recently.
Enjoy ;)
