### ISSUE TITLE
Rocky Helmet Doesn't work

### ISSUE THREAD

**Issue by DiegoVeintisiete** [Farigh/pokeclicker-automation#74]
Every time I put Rocky helmet on my oak items, it is disarmed on the next 5 seconds, happens with automation task active or only with autoclick

**Comment by Farigh** [comment]
Do you, by any chance, have the farming automation enabled, with the advanced setting turned on as well like that : 
![image](https://user-images.githubusercontent.com/11090416/180274642-76cf40df-ff5e-4b8b-b027-1d8a27185c7b.png)

If so, the following berry unlock disables this Oak item : 
  - Payapa 
  - Micle
  - Kebia

This is done to avoid any unwanted mutation.

If it's not your case, could you provide a save reproducing the problem, so I can figure out what happens ?

**Comment by DiegoVeintisiete** [comment]
Gotcha! Yeah I had that option activated, now I put it off and works well, I didn't know that featured. Thanks bro.
