### ISSUE TITLE
New update

### ISSUE THREAD

**Issue by Fyuri13** [Farigh/pokeclicker-automation#75]
### Describe the bug
auto dungeon no longer works due to new update today

**Comment by oohwooh** [comment]
This is due to https://github.com/pokeclicker/pokeclicker/pull/2579 - will submit a PR tomorrow to fix this

**Comment by Farigh** [comment]
I already have a branch ready for this, I'll merge it right now

**Comment by Fyuri13** [comment]
v0.9.9 now
