### ISSUE TITLE
Dungeon: Stop when all chests and the boss were found

### ISSUE THREAD

**Issue by Farigh** [Farigh/pokeclicker-automation#79]
Now that the game shows the remaining chests in the dungeon, their is no point continuing to search the dungeon once all chests and the boss were found.

This should be an advanced option, since shiny farming player might want to clear the dungeon anyway

**Comment by Daniferrito** [comment]
This already happens as of #170.

Both max chests and fights are used to check for objective completion.

To be fair, the only thing missing is checking how many are on each floor, as the game only shows the sum of all floors. This is fixed and not random, so it is a known value (the total amount of fights and chests was always a known value, but it was simply not displayed on the UI)
