### ISSUE TITLE
Any chance of Desktop integration?

### ISSUE THREAD

**Issue by Dessastuff** [Farigh/pokeclicker-automation#84]
### Is your feature request related to a problem? Please describe.
I would love to be able to use this script with the desktop application because it runs in the background while chrome does not

### Describe the solution you'd like
I'd like to be able to watch de movies while the game is running in the background :D

### Describe alternatives you've considered
have tried ot import it and it did not work lol

### Additional context
Just please and thank you :D

**Comment by Farigh** [comment]
I never used the app, I'll see what I can do :)

Do you have any leads to help me start such work ?
