### ISSUE TITLE
Focus: Add more options about the pokeball to use

### ISSUE THREAD

**Issue by Fyuri13** [Farigh/pokeclicker-automation#93]
### Is your feature request related to a problem? Please describe.
Achievement focus turn off caught pokeball setting.I would like the option to choose basic pokeballs for Caught while set to achievement.  This isnt an if you are planning some kind of EV farm setting, but for now id like to be able to passively gain EV while set to achievement farm

**Comment by Fyuri13** [comment]
maybe a global option of which ball to use for caught when not on a quest to use a different ball

**Comment by Farigh** [comment]
I initially did this to avoid leaving an "already caught" ball set where most users might not wan't one.

`The_E364` suggested to be able to choose which ball to use on reddit, I'll start with this one.
Then I'll think about adding an option to choose the default "already caught" ball.
